export const CURSO_SELECTED_NAV = "CURSO_SELECTED_NAV";
export const CARGO_SELECTED_NAV = "CARGO_SELECTED_NAV";
export const EMPRESA_SELECTED_NAV = "EMPRESA_SELECTED_NAV";
export const ESTADO_SELECTED_NAV = "ESTADO_SELECTED_NAV";
export const HABILITACION_SELECTED_NAV = "HABILITACION_SELECTED_NAV";
export const PLAZA_SELECTED_NAV = "PLAZA_SELECTED_NAV";
export const TITULO_SELECTED_NAV = "TITULO_SELECTED_NAV";
export const ZONA_NAVEGACION_SELECTED_NAV = "ZONA_NAVEGACION_SELECTED_NAV";
